"""add teacher class+curriculum preferences

Revision ID: eb0ed055682c
Revises: a8b1a59a0487
Create Date: 2026-04-30 18:39:07.845226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0ed055682c'
down_revision: Union[str, Sequence[str], None] = 'a8b1a59a0487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
