"""Zero-drift test: plesso commuting via DSL vs the legacy
``engine.plessi_constraints.add_plesso_commuting_constraints_for_teacher``.

The DSL form is generated by
``dsl_translator.plesso_commuting_rule_to_dsl`` and consumed by
``DSLConstraintCompiler`` with ``classroom_for_slot`` +
``plessi_data`` carriers (Step 3a). The legacy helper produces
``AddBoolOr([va.Not(), vb.Not()])`` for every adjacent (d, h, h+1)
pair where the teacher would cross plessi against a forbidding rule.

We assert: the two paths produce models with the same set of
feasible solutions on a small, hand-built scenario.
"""
from __future__ import annotations

import os
import sys

import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
ENGINE = os.path.normpath(os.path.join(HERE, "..", "..", "..", "engine"))
WEBUI = os.path.normpath(os.path.join(HERE, "..", ".."))
ROOT = os.path.normpath(os.path.join(HERE, "..", "..", ".."))
for p in (ENGINE, WEBUI, ROOT):
    if p not in sys.path:
        sys.path.insert(0, p)


def _make_plessi_data():
    """A 2-plessi configuration with one teacher commuting rule
    requiring min_gap_hours >= 1 between plessi A (id=1) and B (id=2)."""
    from plessi_constraints import (
        PlessiData, CommutingRule)
    return PlessiData(
        classroom_to_plesso={
            "AulaA1": 1, "AulaA2": 1,
            "AulaB1": 2, "AulaB2": 2,
        },
        teacher_name_to_id={"T1": 100},
        commuting_rules=[
            CommutingRule(
                id=1, from_plesso_id=1, to_plesso_id=2,
                entity_kind="teacher", entity_id=None,
                min_gap_hours=1, allowed_break_only=False,
                break_start_hour=None, break_end_hour=None,
                symmetric=True, priority=0,
            ),
        ],
    )


def _build_basic_model():
    """Build a tiny CP-SAT model with 1 teacher, 1 class, 2 hours
    on day 1, classroom assigned per (cl, d, h):
       (1A, 1, 8) -> AulaA1 (plesso 1)
       (1A, 1, 9) -> AulaB1 (plesso 2)
       (1A, 1, 10) -> AulaA2 (plesso 1)
       (1A, 1, 11) -> AulaB2 (plesso 2)
       (1A, 1, 12..13) -> AulaA1
    Demand: 2 hours of (T1, 1A, Mat) on day 1.
    Without the commuting rule the solver may pick (8, 9) (adjacent
    crossing). With the rule, it must avoid adjacent pairs across
    plessi -> e.g. (8, 12) is fine, (8, 9) forbidden.
    """
    from cp_sat_constraint_model import (
        MonolithicSolver, ConstraintConfig)
    profs = {"T1": {"classi": {"1A": {"Mat": {"ore": 2}}},
                     "max_hours": 18}}
    dc = {("T1", "1A", "Mat", 1): 2}
    classroom_for_slot = {
        ("1A", 1, 8): "AulaA1",
        ("1A", 1, 9): "AulaB1",
        ("1A", 1, 10): "AulaA2",
        ("1A", 1, 11): "AulaB2",
        ("1A", 1, 12): "AulaA1",
        ("1A", 1, 13): "AulaA1",
    }
    cfg = ConstraintConfig(
        enforce_no_holes=False,
        enforce_h3_presence_at_11=False,
        enforce_motorie_pair=False,
        enforce_math_italian_pair=False,
    )
    return MonolithicSolver(
        profs, dc, cfg, classroom_for_slot=classroom_for_slot)


def _enumerate_feasible(ms, *, max_solutions=64):
    """Solve the model and collect every feasible (h_a, h_b) shape
    of the 2 lessons. No objective: enumerate ALL feasible
    solutions (not just optima) so the zero-drift comparison is
    over the constraint set, not over which optimum the solver
    happens to pick."""
    from ortools.sat.python import cp_model
    solver = cp_model.CpSolver()
    solver.parameters.num_search_workers = 1
    solver.parameters.enumerate_all_solutions = True

    found: set[tuple[int, ...]] = set()

    class _Collector(cp_model.CpSolverSolutionCallback):
        def __init__(self, slot, on_sol):
            super().__init__()
            self._slot = slot
            self._on_sol = on_sol
            self.n = 0

        def on_solution_callback(self):
            picked = tuple(sorted(
                k[4] for k, v in self._slot.items()
                if self.Value(v) == 1
            ))
            self._on_sol(picked)
            self.n += 1
            if self.n >= max_solutions:
                self.StopSearch()

    cb = _Collector(ms.slot, found.add)
    solver.parameters.cp_model_presolve = False
    solver.Solve(ms.model, cb)
    return found


def test_plesso_commuting_rule_dsl_smoke():
    """The translator produces parseable DSL for a min_gap=1 rule."""
    from dsl_translator import plesso_commuting_rule_to_dsl
    from webui.backend.utils import general_dsl as gd
    from plessi_constraints import CommutingRule
    rule = CommutingRule(
        id=1, from_plesso_id=1, to_plesso_id=2,
        entity_kind="teacher", entity_id=None,
        min_gap_hours=1, allowed_break_only=False,
        break_start_hour=None, break_end_hour=None,
        symmetric=True, priority=0)
    clauses = plesso_commuting_rule_to_dsl(rule)
    assert len(clauses) == 2  # symmetric -> 2 directed pairs
    for c in clauses:
        gd.parse(c)


def test_plesso_commuting_dsl_zero_drift_vs_legacy():
    """Build the same scenario twice: once with the legacy plessi
    helper, once with DSL clauses generated by
    plesso_commuting_rule_to_dsl. Assert the two models accept the
    SAME set of (h_a, h_b) feasible patterns."""
    from plessi_constraints import (
        add_plesso_commuting_constraints_for_teacher)
    from dsl_translator import plesso_commuting_rule_to_dsl

    plessi = _make_plessi_data()
    rule = plessi.commuting_rules[0]

    # ---- Legacy helper path ----
    ms_legacy = _build_basic_model()
    ms_legacy.add_teacher_no_overlap()
    add_plesso_commuting_constraints_for_teacher(
        ms_legacy.model, ms_legacy.slot, plessi,
        teacher_name="T1",
        days=ms_legacy.days, hours=ms_legacy.hours,
        classroom_for_slot=ms_legacy.classroom_for_slot,
    )
    legacy_solutions = _enumerate_feasible(ms_legacy)

    # ---- DSL path ----
    ms_dsl = _build_basic_model()
    ms_dsl.add_teacher_no_overlap()
    clauses = plesso_commuting_rule_to_dsl(rule)
    for c in clauses:
        ms_dsl.add_dsl_constraint(c, plessi_data=plessi)
    dsl_solutions = _enumerate_feasible(ms_dsl)

    # The DSL formulation may add a tiny amount of slack on edge
    # cases (e.g. when multiple slots share the same (cl, d, h) key
    # they all produce one OR pair via the double-forall path).
    # On the basic 1-cattedra scenario the slot dict is bijective
    # with (cl, d, h), so the two sets should match exactly.
    assert legacy_solutions, (
        f"legacy returned no solutions; check scenario")
    assert dsl_solutions, (
        f"DSL returned no solutions; check scenario")
    assert legacy_solutions == dsl_solutions, (
        f"zero-drift violation;\n"
        f"legacy={sorted(legacy_solutions)}\n"
        f"dsl   ={sorted(dsl_solutions)}")


def test_plesso_commuting_dsl_forbids_adjacent_cross():
    """Sanity check: no feasible solution places the 2 hours at
    (8, 9) when both slots cross plessi (A->B). DSL alone."""
    from dsl_translator import plesso_commuting_rule_to_dsl
    plessi = _make_plessi_data()
    rule = plessi.commuting_rules[0]
    ms = _build_basic_model()
    ms.add_teacher_no_overlap()
    for c in plesso_commuting_rule_to_dsl(rule):
        ms.add_dsl_constraint(c, plessi_data=plessi)
    sols = _enumerate_feasible(ms, max_solutions=128)
    # No (8, 9) solution: pair crosses plessi (A1 -> B1).
    assert (8, 9) not in sols
    assert (9, 10) not in sols  # (B1 -> A2)
    assert (10, 11) not in sols  # (A2 -> B2)
    assert (11, 12) not in sols  # (B2 -> A1)
    # (12, 13) is fine: same plesso A.
    assert (12, 13) in sols


def test_plesso_commuting_no_constraint_when_min_gap_zero():
    """A rule with min_gap_hours=0 and not allowed_break_only is a
    no-op -- the translator returns empty list."""
    from dsl_translator import plesso_commuting_rule_to_dsl
    from plessi_constraints import CommutingRule
    rule = CommutingRule(
        id=2, from_plesso_id=1, to_plesso_id=2,
        entity_kind="teacher", entity_id=None,
        min_gap_hours=0, allowed_break_only=False,
        break_start_hour=None, break_end_hour=None,
        symmetric=True, priority=0)
    assert plesso_commuting_rule_to_dsl(rule) == []


def test_plesso_commuting_per_teacher_filter():
    """When entity_id + teacher_name are provided the DSL uses the
    teacher literal in the where clause (instead of l1.teacher ==
    l2.teacher)."""
    from dsl_translator import plesso_commuting_rule_to_dsl
    from plessi_constraints import CommutingRule
    rule = CommutingRule(
        id=3, from_plesso_id=1, to_plesso_id=2,
        entity_kind="teacher", entity_id=42,
        min_gap_hours=1, allowed_break_only=False,
        break_start_hour=None, break_end_hour=None,
        symmetric=True, priority=0)
    clauses = plesso_commuting_rule_to_dsl(rule, teacher_name="Rossi")
    assert len(clauses) == 2
    for c in clauses:
        assert '"Rossi"' in c, c


def test_plesso_commuting_class_kind_now_supported():
    """class-kind rule now produces DSL clauses bound on l.class
    (finding 15): the class-side helper has landed."""
    from dsl_translator import plesso_commuting_rule_to_dsl
    from plessi_constraints import CommutingRule
    rule = CommutingRule(
        id=4, from_plesso_id=1, to_plesso_id=2,
        entity_kind="class", entity_id=None,
        min_gap_hours=1, allowed_break_only=False,
        break_start_hour=None, break_end_hour=None,
        symmetric=True, priority=0)
    clauses = plesso_commuting_rule_to_dsl(rule)
    assert len(clauses) == 2  # symmetric
    assert all("l2.class == l1.class" in c for c in clauses)
